// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiApp.Data;

#nullable disable

namespace WebApiApp.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220523100753_SeedProductDatas")]
    partial class SeedProductDatas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiApp.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 5, 20, 13, 7, 52, 893, DateTimeKind.Local).AddTicks(9499),
                            Name = "Bilgisayar",
                            Price = 15000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 4, 23, 13, 7, 52, 893, DateTimeKind.Local).AddTicks(9538),
                            Name = "Telefon",
                            Price = 3750m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 5, 8, 13, 7, 52, 893, DateTimeKind.Local).AddTicks(9543),
                            Name = "Tablet",
                            Price = 2500m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 3, 24, 13, 7, 52, 893, DateTimeKind.Local).AddTicks(9547),
                            Name = "Akıllı Saat",
                            Price = 1500m,
                            Stock = 600
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
